function [xdata, ydata] = q1_euler(dx)
% Equation is y'-3y=exp(x), y(0) = 0.
xmax = 3;
n = ceil(xmax/dx); % CALCULATE HOW MANY STEPS ARE NEEDED, BASED ON XMAX AND DX
xdata = dx*(0:n-1); % EASIEST WAY TO CREATE THE EVENLY SPACED GRID WE WANT
ydata = zeros(1,n); % CREATE AN EMPTY VECTOR TO STORE OUR SOLUTION IN
ydata(1) = 0; % SET INITIAL CONDITION
for i = 1:n-1
ydata(i+1) = dx*(exp(xdata(i)) + 3*ydata(i))+ydata(i);
end
% HERE THE FOR-LOOP IS WHAT ACTUALLY EXECUTES THE EULER METHOD.
% EVERYTHING ELSE IS JUST TO SET UP. THE LOOP MARCHES THROUGH TIME, USING
% PREVIOUSLY COMPUTED VALUES OF Y AND X TO COMPUTE THE NEXT VALUES
% ACCORDING TO THE FORWARD EULER METHOD. 
% NOTE THAT THE FUNCTION OUTPUTS BOTH X AND Y
end