function [x,y] = q2b_euler
% USES A SECOND ORDER DIFFERENCE TO SOLVE QUESTION 2. YOU CAN USE TAYLOR
% SERIES TO SHOW THAT 
% Y'(X_N) ~ (Y(X+H)- Y(X-H))/2H + O(H^2)
% THIS MEANS THAT THE METHOD TAKES INFORMATION FROM THE TWO PREVIOUS POINTS
% TO CALCULATE THE NEXT POINT
xmax = 5;
dx = 0.01;
n = ceil(xmax/dx);
x = dx*(0:n-1);
y = zeros(1,n);
y(1) = 1;
% WE HAVE A PROBLEM! THERE IS ONE INITIAL CONDITION SO THE METHOD CAN'T
% START. WE NEED TO CALCULATE THE SECOND ENTRY USING THE FIRST-ORDER METHOD
y(2) = y(1) + dx*sin(y(1)); % NORMAL EULER
for j = 2:n-1
    y(j+1) = y(j-1)+2*dx*sin(y(j)); % APPLY THE SECOND ORDER APPROXIMATION
end
% THE KEY HERE IS THAT THE SECOND-ORDER APPROXIMATION GENERATES Y' BASED ON
% THE PRECEEDING 2 GRIDPOINTS. AS WE ONLY KNOW THE SOLUTION AT ONE
% GRID-POINT, WE NEED TO USE THE FIRST-ORDER APPROXIMATION ON THE FIRST
% STEP TO START THE EQUATION
end